config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks, controller: 'projects/tasks', only:[:create, :destroy] do
      resource :done, controller: 'projects/tasks/done', only:[:update]
  end
  end

  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  validates :title,
  presence: { message: "入力してください"},
  length: { minimum: 3, message: "短すぎ！" }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :title, presence: true

  scope :unfinished, -> { where(done: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects/tasks/done_controller.rb
class Projects::Tasks::DoneController < ApplicationController
  before_action :set_project
  before_action :set_task

  def update
    @task.update(task_params)
    head :ok
  end

  private

  def set_project
    @projects = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:task_id])
  end

  def task_params
    params.require(:task).permit(:done)
  end
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:destroy]

  def create
    @task = Task.new(project: @project);
    @task.assign_attributes(task_params);
    if @task.save
      redirect_to project_path(@project)
    else
      render 'projects/show'
    end
  end

  def destroy
    @task.destroy
    redirect_to project_path(@task.project_id)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
    @task = Task.new(project: @project);
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

	def project_params
	  params.require(:project).permit(:title)
	end

	def set_project
      @project = Project.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects/tasks_helper.rb
module Projects::TasksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>

    <p>
      <%= link_to "Home", '/' %>
    </p>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'shared/form', project: @project %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.title, project_path(project) %>
      (<%= project.tasks.unfinished.count %>/<%= project.tasks.count %>)
      <%= link_to "[Edit]", edit_project_path(project.id) %>
      <%= link_to "[Delete]", project_path(project.id), method: :delete, data: {confirm: "Are You Sure?"} %>
    </li>
  <% end %>
</ul>

    <%= link_to 'Add New', new_project_path %>

app/views/projects/new.html.erb
<h1>Add New</h1>

<%= render 'shared/form', project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<ul>
<% @project.tasks.each do |task| %>
<li>
 <%= check_box_tag "task[done]", true, task.done, {
   data: {
     url: project_task_done_path(@project, task),
     method: :patch,
     remote: true
   },
   onchange: '$(this).data("params", "task[done]=" + this.checked)'
 } %>

<%= task.title %>

</li>
<%= link_to "[Delete]", project_task_path(task.project, task), method: :delete, data: {confirm: "are yue sure?"} %>
<% end %>
  <li>
    <%= form_for [@project, @project.tasks.build] do |f| %>
      <%= f.text_field :title %>
      <%= f.submit %>
    <% end %>
  </li>
</ul>

app/views/shared/_form.html.erb
<%= form_for project do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <% if project.errors.any? %>
    <%= project.errors.messages[:title][0] %>
  <% end %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>